tier4/ros2caret

package.xml
ros2caret/verb/__init__.py
ros2caret/verb/check_caret_rclcpp.py
ros2caret/verb/check_ctf.py
ros2caret/verb/node_summary.py
ros2caret/verb/topic_summary.py
ros2caret/verb/trace_point_summary.py
setup.py

@hsgwa 
お疲れ様です。
[測定後の一括チェックツール作成](https://tier4.atlassian.net/browse/T4PB-17109)が完了したので、ご確認をお願いいたします。
lttng クラスを初期化する際に、Event_Counter クラスの [_validate](https://github.com/tier4/CARET_analyze/blob/f79dfe49c6cbeb81efd8223c6bb41f20b99f74a4/caret_analyze/infra/lttng/event_counter.py#L44) が実行され、LD_PRELOAD によるトレースポイントが入っているかのチェックも実施されるので、特にこのチェックに関して追加実装は不要でした。
サマリ表示では、-c オプションでチェックも兼ねることができるようになっています。（[こちらのスレッドの内容](https://emb4hq.slack.com/archives/C017YM4AA06/p1650940805273969?thread_ts=1650616341.892579&cid=C017YM4AA06)）
また、`lttng.get_count(groupby=['node_name'(または 'topic_name')]) `で取得できる dataframe の "topic_name" や "node_name" が "-" となっている行に関しては、値が取得できなかったものの総和になってしまうと考えたため、表示していません。
以下はコマンド実行時の出力結果です。
https://drive.google.com/drive/folders/1FX67Gl7DF9Jgw7sZorCBKNHyiyDJ5BwV?usp=sharing

feat: CLI for batch check and summary display

---

package.xml
ros2caret/verb/record_sim_time.py
test/test_mypy.py

Signed-off-by: hsgwa <hasegawa.isp@gmail.com>

fix: rename tabulate dependency to rosdep compliant. closes #11

---

requirements.txt

jupyter-server と nbconvert のバージョン差異に起因して、古い ipynb ファイルを jupyter-notebook から開けないことがあったので、nbconvert （と、依存のある nbconvert）の必要バージョンを追記しました。

fix: add nbconvert and nbformat with version

---

.github/workflows/pytest.yaml
package.xml
pytest.ini
ros2caret/verb/check_caret_rclcpp.py
test/test_mypy.py
test/verb/test_check_caret_rclcpp.py

I have removed the logging handler during PR #17  (https://github.com/tier4/ros2caret/pull/17/commits/666bc220cd4991779a75565824e27429dcc6df82 ) so that check caret_rclcpp log message were removed for my mistake.
This PR is a patch to make the log output during caret_rclcpp_check.

fix: check-caret-rclcpp logging output

---

ros2caret/verb/summary.py

Signed-off-by: hsgwa <hasegawa.isp@gmail.com>
This PR fixes following error:
```
autoware@38a3ea7915c2:~/ros2_ws/evaluate$ ros2 caret node_summary -d end_to_end_sample/
Traceback (most recent call last):
File "/opt/ros/galactic/bin/ros2", line 11, in <module>
load_entry_point('ros2cli==0.13.1', 'console_scripts', 'ros2')()
File "/opt/ros/galactic/lib/python3.8/site-packages/ros2cli/cli.py", line 67, in main
rc = extension.main(parser=parser, args=args)
File "/home/autoware/ros2_caret/build/ros2caret/ros2caret/command/caret.py", line 32, in main
return extension.main(args=args)
File "/home/autoware/ros2_caret/build/ros2caret/ros2caret/verb/node_summary.py", line 49, in main
summary.print_summary()
File "/home/autoware/ros2_caret/build/ros2caret/ros2caret/verb/summary.py", line 61, in …
```

fix: lttng has no attribute last filters

---

ros2caret/verb/create_architecture.py
ros2caret/verb/verify_paths.py

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>
The current implementation passes the test in an environment where PYTHONPATH is not set.
However, when PYTHONPATH is set correctly, some tests failue.
1. CaretAnalyzeEnabled is set to true.
2. Architecture('') throws an exception.
This PR fixes to pass all tests.

test: pass test in PYTHONPATH set environment

---

ros2caret/verb/record.py
setup.py

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>
This PR add new CLI:
```bash
ros2 caret record
```
This is just a wrapper of following:
```bash
ros2 trace -k -u "ros*"
```
I'm planning to add some features to `ros2 caret record`
- automatic run clock recorder node
- `ros2 run caret_trace clock_recorder`.
- automatic run node to publish record_start/record_end topic
-  https://github.com/tier4/ros2caret/pull/34
- add caret_light option.

feat: add caret record CLI

---

ros2caret/verb/record.py

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>
This PR fixes an error for keyword arguments.
related: https://github.com/tier4/ros2caret/pull/38

fix(record): positional arguments error

---

ros2caret/verb/create_architecture.py

Signed-off-by: atsushi421 <a.yano.578@ms.saitama-u.ac.jp>
This PR make `--force` option work without argument.

chore: make force option work without argument

---

ros2caret/verb/check_caret_rclcpp.py

This PR modifies non-binary files to be unchecked in `ros2 caret check_caret_rclcpp` command.
This bug was reported in the following ticket: 
https://tier4.atlassian.net/browse/T4PB-22214

fix: fix non-binary files to be unchecked in check_caret_rclcpp

---

pytest.ini

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>
In humble, testing of logs using caplog fails.
This PR is a fix to make caplog test pass in humble as well as galactic.

chore(pytest): add no:launch_testing for caplog test in humble

---

ros2caret/verb/check_caret_rclcpp.py

Signed-off-by: atsushi421 <a.yano.578@ms.saitama-u.ac.jp>
This PR add some ignore file extensions into `ros2 caret check_caret_rclcpp`.
Image when the bug occurs:

chore: add some ignore file extensions into check_caret_rclcpp

---

ros2caret/verb/check_caret_rclcpp.py

Signed-off-by: atsushi421 <a.yano.578@ms.saitama-u.ac.jp>
This PR change standard error output of nm command to `/dev/null`.

fix: change standard error output of nm command

---

ros2caret/verb/record.py

Signed-off-by: takeshi.iwanari <takeshi.iwanari@tier4.jp>
Add light mode ( `ros2 caret record --light` ) to record high level events only.
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-24855)
There seems a problem to visualize message flow

feat: add light mode

---

ros2caret/verb/record.py

- `ros2:dispatch_subscription_callback` trace point is replaced with `ros2:rmw_take` by https://github.com/tier4/CARET_trace/pull/113.
- This PR adds `ros2:rmw_take` to light option filter
https://tier4.atlassian.net/browse/RT2-725
- This PR can be merged prior to https://github.com/tier4/CARET_trace/pull/113 
- Confirmation results: https://github.com/tier4/CARET_trace/pull/113#pullrequestreview-1452073035

feat: add tracepoint for light record

---

setup.py

`list` annotation is added in [this PR](https://github.com/tier4/ros2caret/pull/69/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R7), but description to import module is missed. It works with Python 3.10 where `from __future__ import annotations` is added by default, but it don't work with <Python 3.10.
`from __future__ import annotations` is added
https://tier4.atlassian.net/browse/RT2-896
None

fix: import module for annotations

---

ros2caret/verb/caret_record_init.py
ros2caret/verb/record.py

Since iron-irwini, ros2_tracing has added a non-optional argument `--append-trace` for lttng session start. When append-trace=False, if the directory with the specified session name already exists, an error is output and the process is terminated. Default arguments were set to ensure the same behaviour as before in measurements using CARET.
- https://github.com/tier4/ros2caret/pull/72

feat: support non-optional argument `append-trace`

---

ros2caret/verb/record.py

In CARET(humble), the publisher_handle was held by the ros2:rcl_publish and ros2:rclcpp_publish events.
However, in the ros2/ros2_tracing package, only the ros2:rcl_publish event retains information about the publisher_handle.
The ros2caret package provides a light mode for recording high-level events only.
Since the light mode assumes that ros2:rclcpp_publish holds the publisher_handle, it requires minor fix. 
- In distributions after Iron, record `ros2:rcl_publish` during measurements in light mode.
- https://github.com/tier4/CARET_trace/pull/136
- https://github.com/tier4/CARET_analyze/pull/302
After all checkboxes are checked, anyone who has write …

feat: support light mode for iron

---

ros2caret/verb/caret_record_init.py
ros2caret/verb/record.py

This PR adds option for recording immediately.
If the immediately option is True, the recording starts without waiting for the user to press Enter when the measurement starts.
usage:
```
ros2 caret record --immediate
```
- https://tier4.atlassian.net/browse/RT2-927

feat: add option for record start immediately

---

ros2caret/verb/record.py

This PR adds the `--record-clock` option for launching the node where the /clock topic is stored to use ROS time.
- [Discussion](https://star4.slack.com/archives/C05311Y9L2X/p1696985902870339)
- [Performance evaluation](https://tier4.atlassian.net/wiki/spaces/~6422e65c57f0c028e2f72804/pages/2914091021/clock+recorder)

feat: add record-clock option

---

ros2caret/verb/check_caret_rclcpp.py
ros2caret/verb/check_ctf.py
ros2caret/verb/node_summary.py
ros2caret/verb/topic_summary.py
ros2caret/verb/trace_point_summary.py

remove -d for ros2 caret command 
Jira: https://tier4.atlassian.net/browse/RT2-975

refactor: remove -d for ros2 caret command 

---

ros2caret/verb/record.py

When the "--light" option is specified in the caret trace command, sim_time is added to the trace points.
[https://tier4.atlassian.net/browse/RT2-1083](https://tier4.atlassian.net/browse/RT2-1083)

feat: enable sim_time trace point in light mode

---

ros2caret/verb/check_caret_rclcpp.py
test/verb/test_check_caret_rclcpp.py

In humble, application is need to rebuild with caret-rclcpp when traceing and evaluating the data.
After iron some trace points have been added to the ros2-caret, therefore it is no longer necessary to check if you are building with caret-rclcpp.
If a build validation command `ros2 caret check_caret_rclcpp` is performed, the process is skipped and and exit successfully.

fix(check_caret_rclcpp): skip check_caret_rclcpp for ROS Distributions after iron

---

ros2caret/verb/caret_record_init.py
ros2caret/verb/record.py

Determination method of ROS distribution for iron or rolling replaces to correspond to distribution after iron.

refactor: improvement of ros distribution determination method

---

ros2caret/verb/record.py

- `ros2 caret record --immediate` option had been introduced for recording without keyboard input. In this case, ctrl-c is expected to stop recording.
- However, `input` operation causes exception on environment without standard input, which causes the following errors.
```
Traceback (most recent call last):
File "/opt/ros/humble/bin/ros2", line 33, in <module>
sys.exit(load_entry_point('ros2cli==0.18.7', 'console_scripts', 'ros2')())
File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 89, in main
rc = extension.main(parser=parser, args=args)
File "/home/takeshiiwanari/ros2_caret_ws/build/ros2caret/ros2caret/command/caret.py", line 32, in main
return extension.main(args=args)
File "/home/takeshiiwanari/ros2_caret_ws/build/ros2caret/ros2caret/verb/record.py", line 240, …
```

fix: support environment without std::input to stop recording

---

ros2caret/verb/check_caret_rclcpp.py
ros2caret/verb/check_ctf.py
ros2caret/verb/create_architecture.py
ros2caret/verb/verify_paths.py
test/verb/test_create_architecture.py
test/verb/test_verify_paths.py

Added max_construction_order argument to commands using Architecture-API.
[https://tier4.atlassian.net/browse/RT2-1261](https://tier4.atlassian.net/browse/RT2-1261)

fix: add max_construction_order to the command line argument

---

package.xml
ros2caret/verb/version.py

feat: change method of getting version from setup.py to package.xml

---

ros2caret/verb/record.py

When using the -v option during measurement in a multi-host environment, the total number of processes to be measured becomes None.
https://tier4.atlassian.net/browse/RT2-1593

fix: total number of processes becomes None

---

ros2caret/verb/record.py

- [caret_record_init](https://github.com/tier4/ros2caret/blob/v0.5.12/ros2caret/verb/caret_record_init.py#L45) may return error (False), but error is not handled by [the caller](https://github.com/tier4/ros2caret/blob/v0.5.12/ros2caret/verb/record.py#L224)
- The error happens when `lttng-sessiond --daemonize` fails in [here](https://github.com/tier4/ros2_tracing/blob/humble_tracepoint_added/tracetools_trace/tracetools_trace/tools/lttng_impl.py#L106)
- There are two processes who tries to run `lttng-sessiond --daemonize` when it's not launched
- [~/ros2_caret_ws/setenv_caret.bash](https://github.com/tier4/caret/blob/v0.5.12/ansible/roles/caret/templates/setenv_caret.bash.jinja2#L12)
- [ros2 caret record](https://github.com/tier4/ros2_tracing/blob/humble_tracepoint_added/tracetools_trace/tra …

fix: add retry for init LTTng

---

.github/workflows/pytest.yaml

In pytest.yaml, rosdep is installed but fails due to GPG key expiration.
Because of this, pytest could not run.
- https://github.com/tier4/caret_analyze/pull/569

fix: unable to run pytest in github actions 

---

requirements.txt
ros2caret/verb/verify_paths.py
setup.py

…om tests_require to extras_require.
In setup.py, change the test dependency description from tests_require to extras_require.
[https://github.com/tier4/ros2caret/issues/208](https://github.com/tier4/ros2caret/issues/208)
[https://tier4.atlassian.net/browse/RT0-38753](https://tier4.atlassian.net/browse/RT0-38753)

fix: change tests_require to extras_require in setup.py
